### PR TITLE
Adobrev redesign

### PR DESCRIPTION
**Pull request by AntonDobrev**

### CODE REVIEW

**Comment by TsvetinaIvanova** [comment]
Android version used in Cordova is 4.0.2 but should be 4.1.1.

Remove title tag from index.html.

**Comment by AntonDobrev** [comment]
Comments were addressed.

**Comment by TsvetinaIvanova** [comment]
:+1: and squash the commits.

**Comment by didiepetrova** [comment]
1. ReadMe.md: alt="Try in AppBuilder" title="Try in AppBuilder" -> "Try in the Platform", otherwise :+1:

**Pull request merged**
